const images = {
  AppLogo: () => require('../../src/assets/images/app-logo.png'),
  KhmerFlag: () => require('../../src/assets/images/kh-flag.png'),
  FilterIcon: () => require('../../src/assets/images/filter-icon.png'),
  SaleIcon: () => require('../../src/assets/images/sale-icon.png'),
  HomeIcon: () => require('../../src/assets/images/home-icon.png'),
  ReportIcon: () => require('../../src/assets/images/report-icon.png'),
  EditIcon: () => require('../../src/assets/images/edit-icon.png'),
  PasswordIcon: () => require('../../src/assets/images/change-pass.png'),
  DeleteIcon: () => require('../../src/assets/images/delete-icon.png'),
  PersonIcon: () => require('../../src/assets/images/person-icon.png'),
  LanguageIcon: () => require('../../src/assets/images/language-icon.png'),
  KhmerFlagRadius: () => require('../../src/assets/images/kh-flag-radius.png'),
  EnglishFlagRadius: () =>
    require('../../src/assets/images/uk-flag-radius.png'),
  LogOutIcon: () => require('../../src/assets/images/logout-icon.png'),
  MenuIcon: () => require('../../src/assets/images/menu-icon.png'),
  ListIcon: () => require('../../src/assets/images/list-icon.png'),
  ShiftIcon: () => require('../../src/assets/images/shift-icon.png'),
  DoubleArrowIcon: () => require('../../src/assets/images/double-arrow.png'),
  TopArrow: () => require('../../src/assets/images/top-arrow.png'),
  ExpenseIcon: () => require('../../src/assets/images/expense-icon.png'),
  CustomerReport: () => require('../../src/assets/images/customer-report.png'),
  People: () => require('../../src/assets/images/people.png'),
  StockIcon: () => require('../../src/assets/images/stoke.png'),
  StockAdjustIcon: () => require('../../src/assets/images/stoke-adjust.png'),
  TrendingIcon: () => require('../../src/assets/images/trending.png'),
  ItemReport: () => require('../../src/assets/images/item-report.png'),
  PurchaseIcon: () => require('../../src/assets/images/purchase.png'),
  TableIcon: () => require('../../src/assets/images/table-report.png'),
  PrintIcon: () => require('../../src/assets/images/print-icon.png'),
  DateIcon: () => require('../../src/assets/images/date-icon.png'),
  SettingIcon: () => require('../../src/assets/images/setting.png'),
  TermIcon: () => require('../../src/assets/images/term-icon.png'),
  PrivacyLock: () => require('../../src/assets/images/privacy-lock.png'),
  MenuTabIcon: () => require('../../src/assets/images/menu-tab.png'),
  StaticProductImage: () => require('../../src/assets/images/static-noodle.png'),
  StaticProductImage2: () => require('../../src/assets/images/static-noodle2.png'),
  CachIcon: () => require('../../src/assets/images/cash.png')
};

export default images;
